package com.laul.trackaid.ui.theme

//import androidx.compose.ui.graphics.Color
//
//val backgroundColor = Color(0xFFF0F0F0)
//
//// Modules colors
//val red_primary = Color(0x5B061A)
//val red_secondary = Color(0xCA746A)
//val orange_primary = Color(0xC97507)
//val orange_secondary = Color(0xFFDDB1)
//val blue_primary = Color(0x007771)
//val blue_secondary = Color(0x20C2C2)
//val pink_primary = Color(0x540F56)
//val pink_secondary = Color(0xF3E4EE)
//val grey_primary = Color(0x404446)
//val grey_secondary = Color(0xDEE2E5)


import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB4271C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onPrimaryContainer = Color(0xFF410000)
val md_theme_light_secondary = Color(0xFF9C432E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD2)
val md_theme_light_onSecondaryContainer = Color(0xFF3D0600)
val md_theme_light_tertiary = Color(0xFF99405E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E1)
val md_theme_light_onTertiaryContainer = Color(0xFF3F001B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF321300)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF321300)
val md_theme_light_surfaceVariant = Color(0xFFF5DDDA)
val md_theme_light_onSurfaceVariant = Color(0xFF534341)
val md_theme_light_outline = Color(0xFF857370)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE5)
val md_theme_light_inverseSurface = Color(0xFF522300)
val md_theme_light_inversePrimary = Color(0xFFFFB4A9)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB4271C)
val md_theme_light_surfaceTintColor = Color(0xFFB4271C)

val md_theme_dark_primary = Color(0xFFFFB4A9)
val md_theme_dark_onPrimary = Color(0xFF690001)
val md_theme_dark_primaryContainer = Color(0xFF910806)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_secondary = Color(0xFFFFB4A3)
val md_theme_dark_onSecondary = Color(0xFF5E1606)
val md_theme_dark_secondaryContainer = Color(0xFF7D2C1A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD2)
val md_theme_dark_tertiary = Color(0xFFFFB1C6)
val md_theme_dark_onTertiary = Color(0xFF5E1130)
val md_theme_dark_tertiaryContainer = Color(0xFF7B2947)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF321300)
val md_theme_dark_onBackground = Color(0xFFFFDBC8)
val md_theme_dark_surface = Color(0xFF321300)
val md_theme_dark_onSurface = Color(0xFFFFDBC8)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BE)
val md_theme_dark_outline = Color(0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(0xFF321300)
val md_theme_dark_inverseSurface = Color(0xFFFFDBC8)
val md_theme_dark_inversePrimary = Color(0xFFB4271C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A9)
val md_theme_dark_surfaceTintColor = Color(0xFFFFB4A9)


val seed = Color(0xFF8F0505)
